CREATE DATABASE BEAUTY_SALON default charset utf8;
USE BEAUTY_SALON

CREATE TABLE SERVICE_TYPE (
       ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       NAME VARCHAR(254) NOT NULL);

CREATE TABLE SERVICE_SUBTYPE (
       ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       SERVICE_TYPE_ID INT UNSIGNED NOT NULL,
       NAME VARCHAR(254) NOT NULL,
       TIME_SERVICE TIME);
	   
ALTER TABLE SERVICE_SUBTYPE 
      ADD CONSTRAINT SERVICE_SUBTYPE_TYPE 
	    FOREIGN KEY (SERVICE_TYPE_ID)
        REFERENCES SERVICE_TYPE (ID);

CREATE TABLE PRICE_LIST (
       ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       SERVICE_SUBTYPE_ID INT UNSIGNED NOT NULL,
       COST DOUBLE NOT NULL);
	   
ALTER TABLE PRICE_LIST 
      ADD CONSTRAINT PRICE_LIST_SERVICE_SUBTYPE
	    FOREIGN KEY (SERVICE_SUBTYPE_ID)
        REFERENCES SERVICE_SUBTYPE (ID);	   

CREATE TABLE CLIENT (
       ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       FIRST_NAME VARCHAR(254) NOT NULL,
       MID_NAME VARCHAR(254) NOT NULL,
       LAST_NAME VARCHAR(254) NOT NULL,
       BIRTHDAY DATE NOT NULL,
       TELEPHONE VARCHAR(32) NOT NULL);		   

CREATE TABLE REGISTRATION (
       ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       CLIENT_ID INT UNSIGNED NOT NULL,
       SERVICE_SUBTYPE_ID INT UNSIGNED NOT NULL,
       DATE_SERVICE DATE NOT NULL,
       TIME_SERVICE TIME NOT NULL);
	   
ALTER TABLE REGISTRATION
      ADD CONSTRAINT REGISTRATION_CLIENT 
	    FOREIGN KEY (CLIENT_ID)
	    REFERENCES CLIENT(ID),
      ADD CONSTRAINT REGISTRATION_SERVICE_SUBTYPE 
	    FOREIGN KEY (SERVICE_SUBTYPE_ID)
	    REFERENCES SERVICE_SUBTYPE(ID);

CREATE TABLE PAYMENT (
       ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       PAYMENT_METHOD_ID INT UNSIGNED NOT NULL,
       REGISTRATION_ID INT UNSIGNED NOT NULL,
       PAYMENT_TYPE_ID INT UNSIGNED NOT NULL,
       SUM DOUBLE NOT NULL);
	   
ALTER TABLE PAYMENT
      ADD CONSTRAINT PAYMENT_PAYMENT_METHOD
	    FOREIGN KEY (PAYMENT_METHOD_ID)
	    REFERENCES PAYMENT_METHOD(ID),
      ADD CONSTRAINT PAYMENT_REGISTRATION 
	    FOREIGN KEY (REGISTRATION_ID)
	    REFERENCES REGISTRATION(ID),	  
      ADD CONSTRAINT PAYMENT_PAYMENT_TYPE 
	    FOREIGN KEY (PAYMENT_TYPE_ID)
	    REFERENCES PAYMENT_TYPE(ID);			

CREATE TABLE PAYMENT_TYPE (
       ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       NAME VARCHAR(32) NOT NULL);

CREATE TABLE PAYMENT_METHOD (
       ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       NAME VARCHAR(32) NOT NULL);    